friendly_name = "New Tab - Do No Harm"
description = """
Guardrail metrics for the New Tab. Includes user experience and revenue-related metrics for Search, content and AdMarketplace Sponsored Tiles.
"""


[metrics.newtab_visits.statistics.bootstrap_mean]
[metrics.newtab_visits.statistics.deciles]

[metrics.newtab_engaged_visits.statistics.bootstrap_mean]
[metrics.newtab_engaged_visits.statistics.deciles]

[metrics.newtab_ad_click_rate.statistics.bootstrap_mean]
[metrics.newtab_ad_click_rate.statistics.deciles]

[metrics.newtab_homepage_enabled.statistics.binomial]
[metrics.newtab_engagement.statistics.binomial]
[metrics.newtab_any_searches.statistics.binomial]
[metrics.newtab_gt4_searches.statistics.binomial]

[metrics.sponsored_tile_clicks.statistics.sum]
[metrics.sponsored_tile_clicks.statistics.linear_model_mean]
[metrics.sponsored_tile_impressions.statistics.sum]
[metrics.sponsored_tile_impressions.statistics.linear_model_mean]


[metrics.newtab_organic_topsite_clicks_v2.statistics.sum]
[metrics.newtab_organic_topsite_clicks_v2.statistics.linear_model_mean]
[metrics.newtab_organic_topsite_impressions_v2.statistics.sum]
[metrics.newtab_organic_topsite_impressions_v2.statistics.linear_model_mean]

[metrics.sponsored_content_clicks.statistics.sum]
[metrics.sponsored_content_clicks.statistics.linear_model_mean]
[metrics.sponsored_content_impressions.statistics.sum]
[metrics.sponsored_content_impressions.statistics.linear_model_mean]


[metrics.organic_content_clicks.statistics.sum]
[metrics.organic_content_clicks.statistics.linear_model_mean]
[metrics.organic_content_impressions.statistics.sum]
[metrics.organic_content_impressions.statistics.linear_model_mean]

[metrics.sponsored_tile_ctr.statistics.population_ratio]
numerator='sponsored_tile_clicks'
denominator='sponsored_tile_impressions'

[metrics.sponsored_content_ctr.statistics.population_ratio]
numerator='sponsored_content_clicks'
denominator='sponsored_content_impressions'
