friendly_name = "Pocket in New Tab"
description = "Usage and engagement metrics for Pocket content in New Tab."

[metrics.organic_pocket_clicks.statistics.bootstrap_mean]
[metrics.organic_pocket_clicks.statistics.deciles]

[metrics.sponsored_pocket_clicks.statistics.bootstrap_mean]
[metrics.sponsored_pocket_clicks.statistics.deciles]

[metrics.newtab_searches.statistics.bootstrap_mean]
[metrics.newtab_searches.statistics.deciles]

[metrics.newtab_pocket_enabled.statistics.binomial]
[metrics.newtab_sponsored_pocket_stories_enabled.statistics.binomial]
