version: 1.0.0
about:
  description: Nimbus Feature Manifest for Accounts Web testing
channels:
- developer
features:
  example-feature:
    description: An example feature.
    variables:
      emoji:
        description: An emoji to show for this treatment.
        type: Option<String>
        default: :)
      enabled:
        description: If the feature is enabled.
        type: Boolean
        default: true
