friendly_name = "Default browser"
description = "Metrics that describe whether Firefox for iOS is a user's default browser."


[metrics.opened_as_default]
friendly_name = "Opened as default browser"
description = """
    Fraction of users who opened Firefox through an external link,
    implying the client has Firefox set as the default browser
"""
select_expression = "COALESCE(CAST(SUM(metrics.counter.app_opened_as_default_browser) > 0 AS int), 0)"
data_source = "metrics"
statistics = { binomial = { pre_treatments = ["remove_nulls"] } }


[metrics.default_browser_card_go_to_settings_pressed]
friendly_name = "Go To Settings clicks via onboarding card"
description = """
    Number of clicks on Go To Settings from the default browser onboarding card
"""
select_expression = "SUM(metrics.counter.default_browser_onboarding_go_to_settings_pressed)"
data_source = "metrics"
statistics = { bootstrap_mean = { pre_treatments = ["remove_nulls"] }, deciles = { pre_treatments = ["remove_nulls"] } }

