version: 1.0.0
about:
  description: Nimbus Feature Manifest for Subscription Platform
channels:
- developer
features:
  welcome-feature:
    description: Display a welcome banner on the new Sub Manage page
    variables:
      enabled:
        description: If the feature is enabled.
        type: Boolean
        default: true
