version: 1.0.0
about:
  description: Nimbus Feature Manifest for Subscription Platform
channels:
- production
features:
  free-trial-feature:
    description: Control whether free trials are enabled for payments-next
    variables:
      enabled:
        description: If the feature is enabled.
        type: Boolean
        default: false
  welcome-feature:
    description: Display a welcome banner on the new Sub Manage page
    variables:
      enabled:
        description: If the feature is enabled.
        type: Boolean
        default: false
