data-broker-removal-time-estimates:
  description: Show the data broker removal time estimates
  hasExposure: true
  exposureDescription: ''
  variables:
    enabled:
      type: boolean
      description: If the feature is enabled
example-feature:
  description: An example feature
  hasExposure: true
  exposureDescription: ''
  variables:
    enabled:
      type: boolean
      description: If the feature is enabled
    something:
      type: string
      description: Another variable
landing-page-free-scan-cta:
  description: Landing page free scan CTA
  hasExposure: true
  exposureDescription: ''
  variables:
    enabled:
      type: boolean
      description: If the feature is enabled
    variant:
      type: string
      description: The CTA variant to show
      enum:
      - ctaOnly
      - ctaOnlyAlternativeLabel
      - ctaWithEmail
last-scan-date:
  description: Show the date of the user's last scan in the top right-hand corner
  hasExposure: true
  exposureDescription: ''
  variables:
    enabled:
      type: boolean
      description: If the feature is enabled
welcome-scan-optional-info:
  description: Show additional optional input fields for the data broker scan
  hasExposure: true
  exposureDescription: ''
  variables:
    enabled:
      type: boolean
      description: If the feature is enabled
    variant:
      type: string
      description: The optional fields to show
      enum:
      - middleName
      - none
      - suffix
      - suffixAndMiddleName
