version: 1.0.0
about:
  description: Nimbus Feature Manifest for Monitor Web testing
channels:
- local
features:
  data-broker-removal-time-estimates:
    description: Show the data broker removal time estimates
    variables:
      enabled:
        description: If the feature is enabled
        type: Boolean
        default: true
  example-feature:
    description: An example feature
    variables:
      enabled:
        description: If the feature is enabled
        type: Boolean
        default: true
      something:
        description: Another variable
        type: Option<String>
        default: null
  landing-page-free-scan-cta:
    description: Landing page free scan CTA
    variables:
      enabled:
        description: If the feature is enabled
        type: Boolean
        default: false
      variant:
        description: The CTA variant to show
        type: FreeScanCtaType
        default: ctaWithEmail
  last-scan-date:
    description: Show the date of the user's last scan in the top right-hand corner
    variables:
      enabled:
        description: If the feature is enabled
        type: Boolean
        default: true
  welcome-scan-optional-info:
    description: Show additional optional input fields for the data broker scan
    variables:
      enabled:
        description: If the feature is enabled
        type: Boolean
        default: true
      variant:
        description: The optional fields to show
        type: OptionalBrokerScanInfoFields
        default: middleName
enums:
  FreeScanCtaType:
    description: An enum of free scan CTA types
    variants:
      ctaOnly:
        description: Only show a CTA button with the label “Get free scan”
      ctaOnlyAlternativeLabel:
        description: Only show a CTA button with the label “Sign up to get free scan”
      ctaWithEmail:
        description: Show a CTA button with an optional email input
  OptionalBrokerScanInfoFields:
    description: An enum of optional broker scan info fields
    variants:
      middleName:
        description: Only show the optional middle name field
      none:
        description: Do not show any optional fields
      suffix:
        description: Only show the optional suffix field
      suffixAndMiddleName:
        description: Show the optional suffix and middle name fields
